version: 2.1
orbs:
  node: circleci/node@5

workflows:
  my-workflow:
    jobs:
      - build

jobs:
  build:
    executor: node/default  # Use the default Node.js executor from the orb
    steps:
      - checkout
      - run:
          name: change directory
          command: cd client
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Verify Node.js and npm versions
          command: node -v && npm -v
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Run lint
          command: npm run lint

          